CREATE TABLE Users (
  ID int(11) NOT NULL AUTO_INCREMENT,
  UserName varchar(100) DEFAULT NULL,
  Name varchar(200) DEFAULT NULL,
  RUC int(50) DEFAULT NULL,
  Email varchar(100) DEFAULT NULL,
  Hash varchar(200) DEFAULT NULL,
  Salt varchar(200) DEFAULT NULL,
  RegisterDate datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE Catastro (
  RUC VARCHAR(15) NOT NULL,
  RAZON_SOCIAL VARCHAR(500) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOAD DATA INFILE '/docker-entrypoint-initdb.d/catastro1.csv'
INTO TABLE Catastro
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r'
IGNORE 1 ROWS;

LOAD DATA INFILE '/docker-entrypoint-initdb.d/catastro2.csv'
INTO TABLE Catastro
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r'
IGNORE 1 ROWS;
